version: '3'
services:
  user:
    image: userservice:latest
    container_name: user
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ../configs/config.yaml:/data/conf/config.yaml
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    container_name: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: ccnu
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql  # 持久化 MySQL 数据
  redis:
    image: redis:6.2
    container_name: myredis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  mysql-data:  # 定义 MySQL 数据的持久化 volume
  redis-data:  # 定义 Redis 数据的持久化 volume


# docker-compose up -d
# 初始化 mysql，由于 mysql 没有初始化，所以之后需要重启 user 服务才能正常使用
# docker compose -p myproject restart user