server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    dsn: "root:ccnu@tcp(127.0.0.1:3307)/users?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  database:
    addr: "127.0.0.1:6379"
    password: "ccnu"
    db: 0